# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""The committed parser fixtures are stable and reproducible.

If a library upgrade changes generated bytes, these tests fail: regenerate
with ``uv run python -m tests.fixtures.ingestion.make_fixtures``, review the
parser test results, and commit the new fixtures and SHA256SUMS together.
"""

import pytest

from app.ingestion.hashing import sha256_hex
from tests.fixtures.ingestion.make_fixtures import (
    FIXTURE_DIR,
    FIXTURES,
    MANIFEST,
    build_all,
    manifest_text,
)


def _manifest() -> dict[str, str]:
    lines = (FIXTURE_DIR / MANIFEST).read_text(encoding="utf-8").splitlines()
    return {name: digest for digest, name in (line.split("  ", 1) for line in lines)}


def test_manifest_lists_exactly_the_generated_fixtures() -> None:
    assert set(_manifest()) == set(FIXTURES)


@pytest.mark.parametrize("name", sorted(FIXTURES))
def test_committed_fixture_matches_its_recorded_sha256(name: str) -> None:
    assert sha256_hex((FIXTURE_DIR / name).read_bytes()) == _manifest()[name]


def test_generator_reproduces_the_committed_fixtures_byte_for_byte() -> None:
    rebuilt = build_all()

    mismatched = [n for n, data in rebuilt.items() if (FIXTURE_DIR / n).read_bytes() != data]
    assert mismatched == []
    assert manifest_text(rebuilt) == (FIXTURE_DIR / MANIFEST).read_text(encoding="utf-8")
